
spring.application.name=Learning-Managment-System
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
file.upload-dir=uploads

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saramohamed0103@gmail.com
spring.mail.password=ltcs xles hrjz auwd
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
logging.level.org.springframework.mail=DEBUG
spring.mail.properties.mail.debug=true
# JWT secret key
jwt.secret=c641af642c0da78b3eb0e24b95939a00bfc37dc9a59524af69eba6a57844dfc9

# Token expiration time (1 day)
jwt.expiration=86400000
